### ISSUE TITLE
Double pageviews recorded for GA 4

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-plugin#2085] opened 2022-10-20 07:56 UTC
**Describe the bug**

Continuing discussion from [Site Kit Support thread](https://wordpress.org/support/topic/double-pageviews-recorded-for-ga-4/), raising issue here as it seems site kit is working as intended, only other plugin modifying analytics is newspack set of plugins. This may easily go undetected for website with regular traffic.

Double pageviews are recorded for GA 4 on single page visit. Site is also using Universal Analytics simultaneously which record single page views only. Google Analytics 4 Property Setup Assistant shows that its not connected.

**To Reproduce**
1. For Non-AMP website, enable Universal Analytics and GA4 in Site kit along with newspack set of plugins
2. Use Tag Assistant to monitor events
3. Visit a page
4. See page view event triggered two times for each visit for GA4. Single page view as intended for Universal Analytics

**Screenshots**
For Universal Analytics

![Screenshot](https://user-images.githubusercontent.com/7325107/196889393-1f5538f9-cdfd-4c3d-b508-7a8f10239b0a.png)

For GA4

![Screenshot](https://user-images.githubusercontent.com/7325107/196889489-673d41b0-940d-40b6-8831-94de8141a3e5.png)

**Expected behavior**
Single pageview event should be triggered for GA4, rather than two.

**Comment by adekbadek** [comment] 2022-11-17 15:00
> Use Tag Assistant to monitor events

Is it this [extension](https://chrome.google.com/webstore/detail/tag-assistant-legacy-by-g/kejbdjndbnbjgmefkgdddjlbokphdefk)? The UI looks different.

**Comment by yogeshbeniwal** [comment] 2022-11-18 16:34
It is https://tagassistant.google.com/

**Comment by adekbadek** [comment] 2022-12-13 12:01
That's a false positive, https://github.com/Automattic/newspack-plugin/pull/2188 will resolve it.

**Comment by adekbadek** [comment] 2022-12-19 09:09
Closing because it's [not reproducible](https://github.com/Automattic/newspack-plugin/issues/2085#issuecomment-1337076374).

**Closed by adekbadek** 2022-12-19 09:09 UTC
