### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by MidwestBusiness** [Automattic/newspack-plugin#1430] opened 2022-01-06 21:37 UTC
Hello,
I am working off Newspack version 1.58.0 and would like to update to the most current 1.70.0. In wordpress there is no auto-update option available and when I try to install version 1.70.0 over installed version 1.58.0, it says the directory or plug-in already exists and gives no other options to auto-update.

What is the process to update to the new version? Thank you!

**Comment by adekbadek** [comment] 2022-01-26 09:37
Hi! 

This might have something to do with the file system on the server machine – WP might not be able to write files. The update process should be:

1. Download the latest release ZIP from Github
2. Upload in the WP add-plugin UI

You might also try removing the plugin directory (`wp-content/plugins/newspack-plugin`) and uploading then, at your own risk. Best to get in touch with your systems administrator.

Closing since this is not a bug in the plugin code, but a WP-related issue.

**Closed by adekbadek** 2022-01-26 09:37 UTC
