### ISSUE TITLE
Sign in button not shown on individual posts and pages

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-plugin#1912] opened 2022-08-17 08:06 UTC
**Describe the bug**
Sign in button is shown on home page, but not on individual posts and pages. Show Mobile CTA in Simplfied Subpage Header is enabled.

**Comment by miguelpeixe** [comment] 2022-08-17 13:39
I was not able to reproduce. Can you confirm you're visiting the pages unauthenticated and their are not being affected by cache?

**Comment by yogeshbeniwal** [comment] 2022-08-18 02:17
Testing with unauthenticated user (verified as Sign in button is shown on home page), all caches cleared and serving latest files in incognito mode.

Js and css version is still ?ver=1.80.0, but this may be because of 

https://github.com/Automattic/newspack-plugin/blob/b9fd209191acd8cc460adb6e06c568e76298645b/newspack.php#L17

**Comment by miguelpeixe** [comment] 2022-08-18 15:05
Thank you for catching that @yogeshbeniwal! This will be fixed by https://github.com/Automattic/newspack-plugin/pull/1918

**Comment by adekbadek** [comment] 2022-09-06 09:27
Closed by #1918

**Closed by adekbadek** 2022-09-06 09:27 UTC

**Comment by yogeshbeniwal** [comment] 2022-09-06 10:17
@adekbadek #1918 doesn't solve the issue described in first post. Tested with latest v1.89.1 version.
